# redis-master.redis.svc.cluster.localでアクセス
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: redis
    chart: bitnami/redis
    version: "21.2.14"
    createNamespace: true
    values:
      - global:
          storageClass: "nfs-client"
        auth:
          enabled: false 
        replica:
          replicaCount: 0
      