apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eso-controller
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./clusters/home/packages/eso-controller
  prune: false
  suspend: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eso-config
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./clusters/home/packages/eso-config
  prune: false
  suspend: false
  wait: true
  dependsOn:
    - name: eso-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-secrets-store
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./clusters/home/packages/csi-secrets-store
  prune: false
  suspend: false
  wait: true
  dependsOn:
    - name: eso-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
  annotations:
    flux.takutk.com/activation-blocked: "true"
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  path: ./clusters/home/packages/nextcloud
  prune: false
  suspend: true
  wait: true
  dependsOn:
    - name: eso-controller
    - name: eso-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mortis
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./clusters/home/packages/mortis
  prune: false
  suspend: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trek
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  path: ./clusters/home/packages/trek
  prune: false
  suspend: false
  wait: true
  dependsOn:
    - name: eso-controller
    - name: eso-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memos
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./clusters/home/packages/memos
  prune: false
  suspend: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  path: ./clusters/home/packages/n8n
  prune: false
  suspend: false
  wait: true
  dependsOn:
    - name: eso-controller
    - name: eso-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  path: ./clusters/home/packages/jellyfin
  prune: false
  suspend: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
