# PostgreSQL の設定
postgresql-custom:  # postgresql から postgresql-custom に変更
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  auth:
    username: immich
    database: immich
    password: "your-secure-password"
  primary:
    containerSecurityContext:
      readOnlyRootFilesystem: false
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

# Redis の設定
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

# Immich コンポーネント
server:
  enabled: true
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local  # あなたのドメインに変更してください
          paths:
            - path: /

machine-learning:
  enabled: true
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: emptyDir

# 共通設定
immich:
  persistence:
    library:
      existingClaim: md0  # 既存のPVCの名前を指定 