apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jellyfin-claim
  name: jellyfin-claim
  namespace: jellyfin 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  volumeName: jellyfin-pv
  storageClassName: ""
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: jellyfin 
  labels:
    app: jellyfin
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0
    server: 192.168.11.9