apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: pg

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  refreshInterval: "1h"

  target:
    name: pg-superuser
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "cG9zdGdyZXM=" # postgres - Note: It NEEDs to be postgres
        password: "{{ .postgres_secret }}"

  data:
  - secretKey: postgres_secret
    remoteRef:
      key: postgres-secret
      version: "latest"
      decodingStrategy: None # can be None, Base64, Base64URL or Auto
      
---
# #TODO あとで削除
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: pg-app-user
  namespace: pg
data:
  password: c2VjcmV0X3Bhc3N3b3Jk #secret_password
  username: YXBwX3VzZXI= #app_user