apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: pg
spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: pg-superuser
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: cG9zdGdyZXM= # postgres; CloudNativePG requires this username.
        password: "{{ .postgres_secret }}"
  data:
    - secretKey: postgres_secret
      remoteRef:
        key: postgres-secret
        version: latest
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-app-user
  namespace: pg
spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: pg-app-user
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: app_user
        password: "{{ .app_user_password }}"
  data:
    - secretKey: app_user_password
      remoteRef:
        key: pg-app-user-password
        version: latest
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
