apiVersion: v1
kind: Namespace
metadata:
  name: metube
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.210
  name: metube
  namespace: metube
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: metube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metube
  name: metube
  namespace: metube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      containers:
        - image: ghcr.io/alexta69/metube:2025-05-23
          name: metube
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: metube-pv
              mountPath: /downloads
      volumes:
        - name: metube-pv
          persistentVolumeClaim:
            claimName: metube-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metube-pv
  namespace: metube
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/metube
    server: 192.168.11.9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-pvc
  namespace: metube
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: metube-pv
  resources:
    requests:
      storage: 10Gi
