apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 30m
  timeout: 5m
  suspend: true
  releaseName: csi-secrets-store
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.4.8
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  uninstall:
    keepHistory: true
