apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 30m
  timeout: 5m
  suspend: false
  releaseName: csi-secrets-store
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.4.8
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
    disableHooks: true
    disableTakeOwnership: true
    remediation:
      retries: 0
  upgrade:
    crds: Skip
    disableHooks: true
    disableTakeOwnership: true
    remediation:
      retries: 0
      remediateLastFailure: false
  values:
    linux:
      crds:
        enabled: false
  uninstall:
    keepHistory: true
