apiVersion: v1
kind: PersistentVolume
metadata:
    name: md0
    labels:
        type: md0
spec:
    # capacity:
    #     storage: 5Gi
    accessModes:
        - ReadWriteMany
    capacity: 
      storage: 20Gi
    nfs:
        server: 192.168.11.9
        path: /mnt/md0
        readOnly: false
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfs-storage
