apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app.kubernetes.io/name: alpine
    app.kubernetes.io/part-of: kubernetes-complete-reference
    app.kubernetes.io/created-by: ssbostan
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - sh
        - -c
        - "ls -al /mnt/md0 && tail -f /dev/null"
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/md0
        - name: ssd-nfs-volume
          mountPath: /mnt/ssd
        - name: provisioner-volume
          mountPath: /mnt/provisioner
  volumes:
    - name: nfs-volume
      nfs:
          server: 192.168.11.9
          # directory location on nfs
          path: "/mnt/md0" 
    - name: ssd-nfs-volume
      nfs:
          server: 192.168.11.13
          path: "/srv/nfs4"
    - name: provisioner-volume
      persistentVolumeClaim:
        claimName: test-pvc
