apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore
  refreshInterval: "24h"
  target:
    name: nextcloud-db-secret
    deletionPolicy: Retain
    template:
      data:
        db-username: "nextcloud"
        db-password: '{{ index . "db-password" }}'
        nextcloud-username: "admin"
        nextcloud-password: '{{ index . "admin-password" }}'
        secret: '{{ index . "secret" }}'
        passwordsalt: '{{ index . "passwordsalt" }}'
  data:
    - secretKey: db-password
      remoteRef:
        key: nextcloud-db-password
        version: "latest"
        decodingStrategy: None
    - secretKey: admin-password
      remoteRef:
        key: nextcloud-admin-password
        version: "latest"
        decodingStrategy: None
    - secretKey: secret
      remoteRef:
        key: nextcloud-secret
        version: "latest"
        decodingStrategy: None
    - secretKey: passwordsalt
      remoteRef:
        key: nextcloud-passwordsalt
        version: "latest"
        decodingStrategy: None
