apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database-claim0
  name: database-claim0
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  volumeName: database-pv
  storageClassName: ""
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: immich
  labels:
    app: immich
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/immich/database
    server: 192.168.11.9