#              valueFrom:
#                secretKeyRef:
#                  name: immich-external-secrets
#                  key: immich-db-password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-external-secrets
  namespace: immich

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  # refreshInterval: "1h"

  target:
    name: immich-external-secrets
    deletionPolicy: Retain

  data:
    - secretKey: immich-db-password
      remoteRef:
        key: immich-db-password
        version: "latest"
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
