apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: immich-server-claim0
  name: immich-server-claim0
  namespace: immich
spec:
  storageClassName: ""
  volumeName: immich-upload-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload-pv
  namespace: immich
  labels:
    app: immich
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/immich/photos
    server: 192.168.11.9