apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: immich-server
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: immich-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: immich-server
    spec:
      containers:
        - env:
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE_NAME
                  name: env
            - name: DB_DATA_LOCATION
              value: /var/lib/postgresql/data
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: immich-db-password
                  name: immich-external-secrets
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: env
            - name: UPLOAD_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: UPLOAD_LOCATION
                  name: env
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOSTNAME
                  name: env
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_HOSTNAME
                  name: env
          image: ghcr.io/immich-app/immich-server:v1.135.3
          name: immich-server
          ports:
            - containerPort: 2283
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-server-claim0
            - mountPath: /etc/localtime
              name: immich-server-cm1
              readOnly: true
              subPath: localtime
      restartPolicy: Always
      volumes:
        - name: immich-server-claim0
          persistentVolumeClaim:
            claimName: immich-server-claim0
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: immich-server-cm1
          name: immich-server-cm1
