apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: immich-machine-learning
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: immich-machine-learning
    spec:
      containers:
        - env:
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE_NAME
                  name: env
            - name: DB_DATA_LOCATION
              value: /var/lib/postgresql/data
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-external-secrets
                  key: immich-db-password
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: env
            - name: UPLOAD_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: UPLOAD_LOCATION
                  name: env
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOSTNAME
                  name: env
          image: ghcr.io/immich-app/immich-machine-learning:release
          name: immich-machine-learning
          volumeMounts:
            - mountPath: /cache
              name: model-cache
            - mountPath: /usr/src/app/upload
              name: immich-server-claim0
      restartPolicy: Always
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
        - name: immich-server-claim0
          persistentVolumeClaim:
            claimName: immich-server-claim0
