apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: model-cache
  name: model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: model-cache-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-cache-pv
  namespace: immich
  labels:
    app: immich
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/immich/model_cache
    server: 192.168.11.9