apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
spec:
  ports:
    - port: 6379
  selector:
    io.kompose.service: redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: redis
  name: redis
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/takuto1127/k8s-home-lab/apps/immich/docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: docker.io/redis:6.2-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
          livenessProbe:
            exec:
              command:
                - redis-cli ping || exit 1
          name: immich-redis
      restartPolicy: Always
