apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secrets
  namespace: grafana

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  refreshInterval: "24h"

  target:
    name: grafana-external-secrets
    deletionPolicy: Retain

  data:
    - secretKey: grafana
      remoteRef:
        key: grafana
        version: latest
        decodingStrategy: None
