apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi  # Kubernetesでは容量を指定する必要がありますが、NFSサーバー側で制限を管理します
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.9  # NFSサーバーのIPアドレス
    path: /mnt/md0  # NFSサーバー上のエクスポートされたディレクトリ