apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store-provider
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: gcpsm-secret
      projectID: "269357193809"
