apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: portainer
  labels:
    app: portainer
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/portainer
    server: 192.168.11.9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: portainer
spec:
  storageClassName: ""
  volumeName: portainer-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
