apiVersion: v1
kind: Service
metadata:
  namespace: couchdb 
  name: couchdb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.205
spec:
  type: LoadBalancer
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: couchdb
  name: couchdb
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - image: couchdb:3.4.3
          name: couchdb
          env:
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-external-secrets
                  key: couchdb-password
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-external-secrets
                  key: couchdb-username
          ports:
            - containerPort: 5984
              name: wordpress
          volumeMounts:
            - name: couchdb-persistent-storage
              mountPath: /opt/couchdb/data
      volumes:
        - name: couchdb-persistent-storage
          persistentVolumeClaim:
            claimName: couchdb-pvc
