apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pv
  namespace: couchdb
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ssd/apps/couchdb
    server: 192.168.11.9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: couchdb
spec:
  storageClassName: ""
  volumeName: couchdb-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
