apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-external-secrets
  namespace: couchdb

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  refreshInterval: "1h"

  target:
    name: couchdb-external-secrets
    deletionPolicy: Retain

  data:
    - secretKey: couchdb-password
      remoteRef:
        key: couchdb-password
        version: "latest"
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: couchdb-username
      remoteRef:
        key: couchdb-username
        version: "latest"
        decodingStrategy: None # can be None, Base64, Base64URL or Auto

