apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgvectors
spec:
  interval: 1m
  targetNamespace: database
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: flux-system
  values:
    image:
      repository: tensorchord/pgvecto-rs
      tag: pg16-v0.2.0

    global:
      security:
        allowInsecureImages: true

    auth:
      username: immich
      database: immich
      postgresPassword: "your-postgres-password"    # PostgreSQL adminパスワード
      password: "your-user-password"               # ユーザーパスワード
      replicationPassword: "your-replication-password"  # レプリケーションパスワード

    primary:
      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION cube;
            CREATE EXTENSION earthdistance;
            CREATE EXTENSION vectors;
      persistence:
        enabled: true
        storageClass: "nfs-storage"
        size: 8Gi
        accessModes:
          - ReadWriteOnce
      containerSecurityContext:
        readOnlyRootFilesystem: false
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
        limits:
          cpu: 750m
          memory: 2048Mi
    readReplicas:
      persistence:
        size: 32Gi
      containerSecurityContext:
        readOnlyRootFilesystem: false

volumePermissions:
  enabled: true        # ボリュームの権限を自動的に設定
  securityContext:
    runAsUser: auto
    runAsNonRoot: true