releases:
- name: postgresql
  chart: bitnami/postgresql
  values:
  - ./values.yaml
  set:
    - name: primary.persistence.storageClass
      value: "nfs-client"
    - name: primary.persistence.size
      value: "8Gi"
    - name: volumePermissions.enabled
      value: "true"
    - name: primary.persistence.enabled
      value: "true"
    - name: primary.containerSecurityContext.enabled
      value: "true"
    - name: primary.containerSecurityContext.runAsUser
      value: "1001"