apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primary-pvc # PVCの名前をprimary-pvcとします
spec:
  accessModes:
    - ReadWriteOnce # アクセスモードをReadWriteOnceに設定します
  resources:
    requests:
      storage: 8Gi # ストレージサイズを8Giに設定します
  storageClassName: nfs-client # ストレージクラスをnfs-clientに設定します