apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: dawarich
    labels:
        io.kompose.service: dawarich-public
    name: dawarich-public
spec:
    storageClassName: ""
    volumeName: dawarich-public-pv
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 400Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: dawarich-public-pv
    namespace: dawarich
spec:
    capacity:
        storage: 600Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nfs:
        path: /mnt/md0/apps/dawarich/public/
        server: 192.168.11.9
