apiVersion: v1
kind: Service
metadata:
  name: dawarich-redis
  namespace: dawarich
spec:
  ports:
    - port: 6379
  selector:
    io.kompose.service: dawarich-redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dawarich
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dawarich-redis
  name: dawarich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dawarich-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: dawarich-redis
    spec:
      containers:
        - args:
            - redis-server
          image: redis:8.2-alpine
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: dawarich-redis
          volumeMounts:
            - mountPath: /data
              name: dawarich-shared
      restartPolicy: Always
      volumes:
        - name: dawarich-shared
          persistentVolumeClaim:
            claimName: dawarich-shared