apiVersion: v1
kind: Pod
metadata:
  namespace: dawarich
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dawarich-sidekiq
  name: dawarich-sidekiq
spec:
  containers:
    - args:
        - sidekiq
      command:
        - sidekiq-entrypoint.sh
      env:
        - name: APPLICATION_HOSTS
          value: localhost
        - name: APPLICATION_PROTOCOL
          value: http
        - name: BACKGROUND_PROCESSING_CONCURRENCY
          value: "10"
        - name: DATABASE_HOST
          value: dawarich-db
        - name: DATABASE_NAME
          value: dawarich_development
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dawarich-secrets
              key: dawarich-db-password
        - name: DATABASE_USERNAME
          value: postgres
        - name: DISTANCE_UNIT
          value: km
        - name: ENABLE_TELEMETRY
          value: "false"
        - name: PROMETHEUS_EXPORTER_ENABLED
          value: "false"
        - name: PROMETHEUS_EXPORTER_HOST
          value: dawarich_app
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://dawarich-redis:6379/0
      image: freikin/dawarich:latest
      livenessProbe:
        exec:
          command:
            - bundle exec sidekiqmon processes | grep ${HOSTNAME}
        failureThreshold: 30
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
      name: dawarich-sidekiq
      resources:
        limits:
          cpu: 500m
          memory: "4294967296"
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /var/app/public
          name: dawarich-public
        - mountPath: /var/app/tmp/imports/watched
          name: dawarich-watched
  restartPolicy: OnFailure
  volumes:
    - name: dawarich-public
      persistentVolumeClaim:
        claimName: dawarich-public
    - name: dawarich-watched
      persistentVolumeClaim:
        claimName: dawarich-watched
