apiVersion: v1
kind: Service
metadata:
  namespace: dawarich
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
    metallb.universe.tf/loadBalancerIPs: 192.168.11.202
  labels:
    io.kompose.service: dawarich-app
  name: dawarich-app
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: dawarich-app
