apiVersion: v1
kind: Service
metadata:
  name: dawarich-db
  namespace: dawarich
spec:
  ports:
    - port: 3306
  selector:
    io.kompose.service: dawarich-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dawarich
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dawarich-db
  name: dawarich-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dawarich-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: dawarich-db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dawarich-secrets
                  key: dawarich-db-password
            - name: POSTGRES_USER
              value: postgres
          image: postgis/postgis:14-3.5-alpine
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready -U postgres -d dawarich_development
          #   failureThreshold: 5
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 10
          name: dawarich-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dawarich-db-data
            - mountPath: /var/shared
              name: dawarich-shared
      restartPolicy: Always
      volumes:
        - name: dawarich-db-data
          persistentVolumeClaim:
            claimName: dawarich-db-data
        - name: dawarich-shared
          persistentVolumeClaim:
            claimName: dawarich-shared
