apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dawarich
  labels:
    io.kompose.service: dawarich-watched
  name: dawarich-watched
spec:
  storageClassName: ""     
  volumeName: dawarich-watched-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dawarich-watched-pv
  namespace: dawarich
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/apps/dawarich/watched/
    server: 192.168.11.9