apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dawarich-secrets
  namespace: dawarich

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  refreshInterval: "1h"

  target:
    name: dawarich-secrets
    deletionPolicy: Retain

  data:
    - secretKey: dawarich-db-password
      remoteRef:
        key: dawarich-db-password
        version: "latest"
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
