apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-secrets
  namespace: trek
spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: trek-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: trek-encryption-key
        version: latest
        decodingStrategy: None
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: trek-admin-email
        version: latest
        decodingStrategy: None
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: trek-admin-password
        version: latest
        decodingStrategy: None
