apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: automatisch
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: main
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: main
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: main
    spec:
      containers:
        - command:
            - /compose-entrypoint.sh
          env:
            - name: APP_ENV
              value: production
            - name: HOST
              value: localhost
            - name: PORT
              value: "3000"
            - name: POSTGRES_DATABASE
              value: automatisch
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: automatisch_password
            - name: POSTGRES_USERNAME
              value: automatisch_user
            - name: PROTOCOL
              value: http
            - name: REDIS_HOST
              value: redis
          image: main
          name: main
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /automatisch/storage
              name: automatisch-storage
      restartPolicy: Always
      volumes:
        - name: automatisch-storage
          persistentVolumeClaim:
            claimName: automatisch-storage
