apiVersion: v1
kind: Service
metadata:
  namespace: automatisch
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.204
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: main
  name: main
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: main
  type: LoadBalancer