apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-helmfile
  namespace: argocd # Argo CDがインストールされているnamespace
  labels:
    app.kubernetes.io/name: cmp-helmfile
    app.kubernetes.io/part-of: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-helmfile
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo "Initializing..."']
      generate:
        command: ["helmfile", "template", "--include-crds", "--skip-tests"] 
      discover:
        fileName: "helmfile.yaml"
      allowConcurrency: true
      lockRepo: false