apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-external-secrets
  namespace: wordpress

spec:
  secretStoreRef:
    name: secret-store-provider
    kind: ClusterSecretStore # or ClusterSecretStore

  refreshInterval: "24h"

  target:
    name: wordpress-external-secrets
    deletionPolicy: Retain

  data:
    - secretKey: wordpress-external-secrets
      remoteRef:
        key: wordpress-dbpassword
        version: "latest"
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
