apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress
  labels:
    app: wordpress
spec:
  capacity:
    storage: 13Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/md0/wordpress/
    server: 192.168.11.9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  storageClassName: ""     
  volumeName: wordpress-pv 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 13Gi