# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   namespace: wordpress
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: nfs-client
  # volumeName: wordpress-pv # Remove this line for dynamic provisioning

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress
  labels:
    app: wordpress
spec:
  capacity:
    storage: 13Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # 削除時にデータを保持する
  nfs:
    path: /mnt/md0/wordpress/   # 固定のディレクトリパス
    server: 192.168.11.9    # あなたの NFS サーバーのホスト名または IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  storageClassName: ""      # 動的プロビジョニングを無効化するために空にする
  volumeName: wordpress-pv  # この PV を明示的に指定
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 13Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: wordpress
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: nfs-client